[platformio]
; lib_dir = ../..
; libdeps_dir = workspace_dir/libdeps

[env:disco_f429zi]
platform = ststm32
board = disco_f429zi
framework = stm32cube

; debug_tool = jlink

; SWD interface
; upload_protocol = jlink

debug_tool = stlink
upload_protocol = stlink

monitor_speed = 115200
monitor_raw = true

board_build.mcu = stm32f429zit6
board_build.f_cpu = 180000000L
; board_build.f_cpu = 180000000L
build_flags =
    -D HSE_VALUE=12000000UL
    ;; for oled_ssd1315
    ; Для OLED дисплея:
    -DOLED_SSD1315_ENABLE=1
    ; Для STM32 HAL:
    -DOLED_PLATFORM_STM32HAL=1
    -DSTM32F4
    ; -Wall -Wextra -Werror -Wno-missing-field-initializers
    -D USE_FULL_LL_DRIVER
    -D FIRMWARE_VERSION="\"0.1.0\""
    ; -u _printf_float
    -std=c++1z ; for vt_kalman

board_build.ldscript = STM32F429ZITX_FLASH.ld

lib_deps = 
    ; electricui/electricui-embedded@^0.8.0
    ; marcinbor85/MicroShell@^0.1.0
    ; boriasrazor/oled_ssd1315@^3.0.1
    ; oled_ssd1315
    ; romeric/Fastor@^0.6.3
